##配置数据源
#spring:
#  #文件大小 MB必须大写
#  #  maxFileSize 是单个文件大小
#  #  maxRequestSize是设置总上传的数据大小
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 20MB
#      max-request-size: 20MB
#  datasource:
#    druid:
#      db-type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      url: jdbc:log4jdbc:mysql://10.10.9.13:3306/dora?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      username: dora
#      password: vlKcQf8aLt4NLw@HweM
#      # 初始连接数
#      initial-size: 5
#      # 最小连接数
#      min-idle: 10
#      # 最大连接数
#      max-active: 20
#      # 获取连接超时时间
#      max-wait: 5000
#      # 连接有效性检测时间
#      time-between-eviction-runs-millis: 60000
#      # 连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      # 连接在池中最大生存的时间
#      max-evictable-idle-time-millis: 900000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      # 检测连接是否有效
#      validation-query: select 1
#      # 配置监控统计
#      webStatFilter:
#        enabled: true
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#      filter:
#        stat:
#          enabled: true
#          # 记录慢SQL
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
#  redis:
#    password: GsEnC52019b
#    cluster:
#      nodes:
#      - 10.10.9.12:7000
#      - 10.10.9.12:7001
#      - 10.10.9.12:7002
#      - 10.10.9.12:7003
#      - 10.10.9.12:7004
#      - 10.10.9.12:7005
#      max-redirects: 3  # 获取失败 最大重定向次数
#    lettuce:
#      shutdown-timeout: 100 # 关闭超时时间
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10    # 连接池中的最大空闲连接
#        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle:  5     # 连接池中的最小空闲连接
#    #连接超时时间
#    timeout: 6000
#
#
##jwt
#jwt:
#  header: Authorization
#  # 令牌前缀
#  token-start-with: Bearer
#  # 必须使用最少88位的Base64对该令牌进行编码
#  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
#  # 令牌过期时间 此处单位/毫秒 ，默认10分钟，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
#  token-validity-in-seconds: 600000
#  # 在线用户key
#  online-key: 'online::'
#  # 验证码
#  code-key: 'code::'
#  # token 续期检查时间范围（默认5分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
#  detect: 300000
#  # 续期时间范围，默认10分钟，单位毫秒
#  renew: 600000
#
##市民云信息
#smy:
#  client_id: 4UWIOyjTRh
#  client_secret: 1mdyV9JNU1e1aSgK25kHu0DAtWL6cK0iwYCL4spw
#  grant_type: authorization_code
#  redirect_uri: https://testlife.eshimin.com/frontend/circle/
#  user_basic_uri: https://testlife.eshimin.com/cauth/user/basic
#  user_identity_uri: https://testlife.eshimin.com/cauth/oauth/user/identity
#  token_uri: https://testlife.eshimin.com/cauth/oauth/token
#
#beagle:
#  # 前后端交互是否加密AES+RSA混合加密
#  encrypt: true
#  rsa:
#    # 前后端交互RSA2048公钥、私钥配置
#    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvH9TKTc/zATVu9Bo0YeJ281UaLHZkT4xlGh/guP6D5pS2aXqDsuG16MmNU6Po5IXOuya4qDeNJCg3HGmsCF5una56JaUv4QV//FqNeXYzVX3DvPF3/CmxN8VtzUn/N6zs150b/fGHPGFjLDpCyzM3DI8Pb1hOTmoJQuNUGWKgTcOYthndLHtJI+SEvlqzhIJi91wGjwjifibv3ulJS8hn0GoX8mfTprIncGD7iAOIfjz0gkH7xkGYnHtoriCLbUJhyf7uwe7I7ZoDZdjN5fp+r8nFV7Io1NNnmWfLSFMpq7tQ+OFB7vJY6ZzuDc8sxKbQQDHrBGgnlaYuAZTA0EijQIDAQAB
#    private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8f1MpNz/MBNW70GjRh4nbzVRosdmRPjGUaH+C4/oPmlLZpeoOy4bXoyY1To+jkhc67JrioN40kKDccaawIXm6drnolpS/hBX/8Wo15djNVfcO88Xf8KbE3xW3NSf83rOzXnRv98Yc8YWMsOkLLMzcMjw9vWE5OaglC41QZYqBNw5i2Gd0se0kj5IS+WrOEgmL3XAaPCOJ+Ju/e6UlLyGfQahfyZ9OmsidwYPuIA4h+PPSCQfvGQZice2iuIIttQmHJ/u7B7sjtmgNl2M3l+n6vycVXsijU02eZZ8tIUymru1D44UHu8ljpnO4NzyzEptBAMesEaCeVpi4BlMDQSKNAgMBAAECggEAQdAq1v8lVTRy86pmjpHGPmpIiG1gS2fto6WAr9CtZHk7aCaXvCavo+ag1ofhevjtB3PI+Eu2iZ/dqlo8Gs71U3dUnbLFqMCTddNyg/MGaVsUcbIHapL5h09ko5z5oz6We5AFE3rtPvnM6TxzgaVYuaEIi33tzi8lWBnaczGg1FAtIzxMWVi7iPXnthiHaUULIzbfgR2NikompuuaNCFHWa4/e8xM80leK4TZbcedhDs/cds6VYCrYbmMBQoJi69b0xP+uuovtSkUxmCd0bLgIZSUhQet6Cj4O13/pZSQIAa19tXg9LgnZmZJJ2Q7zVFeINeVB9aAaaKGcreyNH09QQKBgQDoB80vFa3BKp5vK/kZy4IrSO4x4OPY37PFhHFnpWsy1vcYbJ8q7nh6H7CWtj7RI/HQFiqie6v33pOaEUM2M1AKG5bvi+ISuFX0SrwyQ/MqzIgFvUunDYTPeRyfBVrkK3JYkHUrILrhmL3awrRJ+UWzxuXyiGYJlBhoHDDBidaARQKBgQDP+EL2bx1bXxYSMA4a+ZtMMLLA659TuqEDmLOiQnv0vvcQz5GNpGvFogjn0ZbHp/Ctk/ckQyw/Mz0RX9nHhGt9/pOlM4AGt8Iq3gbu9l2YFcuop3Bh6sHYm1Bwu2hG6UsO2tBhnYJqGjBn8AOSj2hmHvMYRdfYpNkprkUq8mhxqQKBgFKKw/FmEuPO14HQ8NK+VNY1IZdY23VBT2CKlxU6AYKaeliT+6N4Jh+7ukRDHOGlmdZerFgVCr4ozfVXAsP7SRPvcKhS6N+j99/p3j07cvvcut7f0lPhOUfdW9MuQoE8+3aKHUR0Zkbu4Us7TIusQ6GKti6rWzE5H92Zeba/5DDJAoGBAJeks9cTgHl+pQ5QAgkDVozAuabYaE3aOMvxjZJUHiSBFpAoej6o1HjARPQcLHCa8XDwAnZrkJjo2K+Rj6/ey66MccY0/jZnyWoOiUm3VNmvktgAd36+eehin84DqO6D79n+DZIQEucg/4jaRxCYBwznpmRdkR0EXuD4lLDTHvs5AoGBAKSnEGctzkzAMgAhXYCamAnOJYNMnfikmFkARPOnb4eL5fxIMjRIaOF5UnirGESkd7N0EFcJReWPJgqFI56J7+1izdRFx65dnRVBwRPREFZiHNF92E8GNDfkZ7cv0p3163HzjGqw/bhoCa0o4xJpXNS+eiC4c++N/UhHn1kmrrCV
#
##中台信息
#middle:
#  use: false
#  url: https://api.wioc.cn/ver/sq
#
##白名单信息
#cors:
#  allowed:
#    origin : https://testlife.eshimin.com
#
## 文件存储路径
#file:
#  allowFileType: bmp,jpg,png,gif,svg,avi,mov,rmvb,mp4,mpeg,wmv,mpg
#  allowFileSize: 10000000
#  local:
#    mac:
#      path: ~/file/
#      avatar: ~/avatar/
#    linux:
#      path: /www/html/ver/swjd/file/
#      avatar: /www/html/ver/swjd/avatar/
#    windows:
#      path: E:\beagle\file\
#      avatar: E:\beagle\avatar\
#    # 文件大小 /M
#    maxSize: 100
#    avatarMaxSize: 5
#  ftp:
#    host: 101.231.159.189
#    port: 7021
#    user: wioc
#    password: Wioc_2020!
#    uploadPath: /www/ftp-files/wioc/u/cn/sh
#    cdnUrl: https://cdn.wioc.cn/u/cn/sh
#  # 云化环境 统一对象存储
#  api:
#    uploadUrl: https://testlife.eshimin.com/coss/upload
#  # 部门环境 WIOC平台文件上传
#  wioc:
#    url: https://api.wioc.cn/ver/api/plat/wioc/V1/file/upload
#    token: wioc_a_plat
#    origin: https://ver.wioc.cn
#
##百度API信息
#baidu:
#  api_key: uxQjGOLmGsEtyy5CSgakh0iK
#  secret_key: Vve0ktPsDmOsfk3nZZhgTi1uOZeCMrHz
#
##日志文件存储
#logging:
#  file:
#    path: c:\\logs
#
##审核状态
#needAudit: false
